### ISSUE TITLE
Handle Ctrl+C better

### ISSUE THREAD

**Issue by FichteFoll** [chireiden/shanghai#14]
```
Traceback (most recent call last):
  File "launch.py", line 4, in <module>
    main()
  File "E:\Development\Python\shanghai\shanghai\main.py", line 30, in main
    loop.run_until_complete(asyncio.wait(tasks))
  File "c:\python35\Lib\asyncio\base_events.py", line 330, in run_until_complete
    self.run_forever()
  File "c:\python35\Lib\asyncio\base_events.py", line 301, in run_forever
    self._run_once()
  File "c:\python35\Lib\asyncio\base_events.py", line 1162, in _run_once
    event_list = self._selector.select(timeout)
  File "c:\python35\Lib\selectors.py", line 314, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "c:\python35\Lib\selectors.py", line 305, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt
<_WindowsSelectorEventLoop running=False closed=True debug=False>
{'task': <Task pending coro=<Network.start() running at E:\Development\Python\shanghai\shanghai\network.py:80> wait_for=
<_GatheringFuture pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at c:\python35\Lib\asyncio\tasks.py:4
00]>, 'message': 'Task was destroyed but it is pending!'}
Unhandled error in exception handler
context: {'task': <Task pending coro=<Network.start() running at E:\Development\Python\shanghai\shanghai\network.py:80>
wait_for=<_GatheringFuture pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at c:\python35\Lib\asyncio\t
asks.py:400]>, 'message': 'Task was destroyed but it is pending!'}
Traceback (most recent call last):
  File "c:\python35\Lib\asyncio\base_events.py", line 1066, in call_exception_handler
    self._exception_handler(self, context)
  File "E:\Development\Python\shanghai\shanghai\main.py", line 11, in exception_handler
    raise context['exception']
KeyError: 'exception'
<_WindowsSelectorEventLoop running=False closed=True debug=False>
{'task': <Task pending coro=<Client.run() running at E:\Development\Python\shanghai\shanghai\client.py:44> wait_for=<Fut
ure pending cb=[Task._wakeup()]> cb=[Network.runner_task_done(), gather.<locals>._done_callback(0)() at c:\python35\Lib\
asyncio\tasks.py:602]>, 'message': 'Task was destroyed but it is pending!'}
Unhandled error in exception handler
context: {'task': <Task pending coro=<Client.run() running at E:\Development\Python\shanghai\shanghai\client.py:44> wait
_for=<Future pending cb=[Task._wakeup()]> cb=[Network.runner_task_done(), gather.<locals>._done_callback(0)() at c:\pyth
on35\Lib\asyncio\tasks.py:602]>, 'message': 'Task was destroyed but it is pending!'}
Traceback (most recent call last):
  File "c:\python35\Lib\asyncio\base_events.py", line 1066, in call_exception_handler
    self._exception_handler(self, context)
  File "E:\Development\Python\shanghai\shanghai\main.py", line 11, in exception_handler
    raise context['exception']
KeyError: 'exception'
<_WindowsSelectorEventLoop running=False closed=True debug=False>
{'task': <Task pending coro=<Network.worker() running at E:\Development\Python\shanghai\shanghai\network.py:119> wait_fo
r=<Future pending cb=[Task._wakeup()]> cb=[Network.worker_task_done(), gather.<locals>._done_callback(1)() at c:\python3
5\Lib\asyncio\tasks.py:602]>, 'message': 'Task was destroyed but it is pending!'}
Unhandled error in exception handler
context: {'task': <Task pending coro=<Network.worker() running at E:\Development\Python\shanghai\shanghai\network.py:119
> wait_for=<Future pending cb=[Task._wakeup()]> cb=[Network.worker_task_done(), gather.<locals>._done_callback(1)() at c
:\python35\Lib\asyncio\tasks.py:602]>, 'message': 'Task was destroyed but it is pending!'}
Traceback (most recent call last):
  File "c:\python35\Lib\asyncio\base_events.py", line 1066, in call_exception_handler
    self._exception_handler(self, context)
  File "E:\Development\Python\shanghai\shanghai\main.py", line 11, in exception_handler
    raise context['exception']
KeyError: 'exception'
<_WindowsSelectorEventLoop running=False closed=True debug=False>
{'transport': <_SelectorSocketTransport fd=544>, 'exception': OSError(10038, 'Ein Vorgang bezog sich auf ein Objekt, das
 kein Socket ist', None, 10038, None), 'message': 'Fatal write error on socket transport', 'protocol': <asyncio.sslproto
.SSLProtocol object at 0x00000000033D7CC0>}
Unhandled error in exception handler
context: {'transport': <_SelectorSocketTransport fd=544>, 'exception': OSError(10038, 'Ein Vorgang bezog sich auf ein Ob
jekt, das kein Socket ist', None, 10038, None), 'message': 'Fatal write error on socket transport', 'protocol': <asyncio
.sslproto.SSLProtocol object at 0x00000000033D7CC0>}
Traceback (most recent call last):
  File "c:\python35\Lib\asyncio\base_events.py", line 1066, in call_exception_handler
    self._exception_handler(self, context)
  File "E:\Development\Python\shanghai\shanghai\main.py", line 11, in exception_handler
    raise context['exception']
  File "c:\python35\Lib\asyncio\selector_events.py", line 698, in write
    n = self._sock.send(data)
OSError: [WinError 10038] Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist
<_WindowsSelectorEventLoop running=False closed=True debug=False>
{'transport': <_SelectorSocketTransport closing fd=544>, 'exception': RuntimeError('Event loop is closed',), 'message':
'Fatal error on SSL transport', 'protocol': <asyncio.sslproto.SSLProtocol object at 0x00000000033D7CC0>}
Unhandled error in exception handler
context: {'transport': <_SelectorSocketTransport closing fd=544>, 'exception': RuntimeError('Event loop is closed',), 'm
essage': 'Fatal error on SSL transport', 'protocol': <asyncio.sslproto.SSLProtocol object at 0x00000000033D7CC0>}
Traceback (most recent call last):
  File "c:\python35\Lib\asyncio\base_events.py", line 1066, in call_exception_handler
    self._exception_handler(self, context)
  File "E:\Development\Python\shanghai\shanghai\main.py", line 11, in exception_handler
    raise context['exception']
  File "c:\python35\Lib\asyncio\selector_events.py", line 698, in write
    n = self._sock.send(data)
OSError: [WinError 10038] Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35\Lib\asyncio\base_events.py", line 1066, in call_exception_handler
    self._exception_handler(self, context)
  File "E:\Development\Python\shanghai\shanghai\main.py", line 11, in exception_handler
    raise context['exception']
  File "c:\python35\Lib\asyncio\sslproto.py", line 624, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python35\Lib\asyncio\selector_events.py", line 702, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "c:\python35\Lib\asyncio\selector_events.py", line 590, in _fatal_error
    self._force_close(exc)
  File "c:\python35\Lib\asyncio\selector_events.py", line 602, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "c:\python35\Lib\asyncio\base_events.py", line 453, in call_soon
    handle = self._call_soon(callback, args)
  File "c:\python35\Lib\asyncio\base_events.py", line 462, in _call_soon
    self._check_closed()
  File "c:\python35\Lib\asyncio\base_events.py", line 289, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by FichteFoll** [comment]
Will be fixed via:
https://github.com/chireiden/shanghai/commit/d2d94fa76af48b6945880b7dfbefbed8dbc00db1
https://github.com/chireiden/shanghai/commit/220c059a065e5a6ffbb750b92f8cd4e74520fdc3
https://github.com/chireiden/shanghai/commit/2b8c9a108f331a16cd6b1d674f9c457c5041a89c
